### ISSUE TITLE
how can we deploy to other free servers like railway, render, codecapsules etc?

### ISSUE THREAD

**Issue by askfriends** [bunnykek/MediaInfoBot#1]

**Comment by bunnykek** [comment]
yes. use the dockerFile to build and deploy the bot.
You need to set ENV variables manually.

**Comment by askfriends** [comment]
> yes. use the dockerFile to build and deploy the bot. You need to set ENV variables manually.

will u add all required files and deploy to buttons for easy deployment?
or some guide explaining how to deploy on thise servers?
thanks

**Comment by bunnykek** [comment]
Current I dont have time for doing these things. You can Google search these common queries.

**Comment by askfriends** [comment]
> Current I dont have time for doing these things. You can Google search these common queries.

I will try my best, btw can u clarify it downloads the video or audio file to the server and then generate mediainfo?

**Comment by bunnykek** [comment]
Obviously ok the server.
Also it only downloads first few chunks(~1MB)
